# LOOKUPS

WEIGHT_TARGETS = {
    'Knee_L': 'DEF-shin.L',
    'Knee_R': 'DEF-shin.R',
    'Elbow_L': 'DEF-forearm.L',
    'Elbow_R': 'DEF-forearm.R',
}

WEIGHT_LOOKUP = {
    'Leg_1_L': 'DEF-thigh.L',
    'Leg_1_R': 'DEF-thigh.R',
    'Leg_Assist_L': 'DEF-thigh.L.001',
    'Leg_Assist_R': 'DEF-thigh.R.001',
    'Leg_2_L': 'DEF-shin.L',
    'Leg_2_R': 'DEF-shin.R',
    'Ankle_L': 'DEF-foot.L',
    'Ankle_R': 'DEF-foot.R',
    'Ankle_Assist_L': 'DEF-shin.L.001',
    'Ankle_Assist_R': 'DEF-shin.R.001',
    'Toe_L': 'DEF-toe.L',
    'Toe_R': 'DEF-toe.R',

    # Spine
    'Waist': 'DEF-spine',
    'Spine_1': 'DEF-spine.001',
    'Spine_2': 'DEF-spine.002',
    'Spine_3': 'DEF-spine.003',
    'Neck': 'DEF-spine.004',

    # Head and head-related
    'Head': 'DEF-spine.006',
    'Head_Root': 'DEF-spine.006',  # This especially for eyebrows

    # Shoulders & Arms
    'Clavicle_L': 'DEF-shoulder.L',
    'Clavicle_R': 'DEF-shoulder.R',
    'Arm_Assist_L': 'DEF-upper_arm.L',
    'Arm_Assist_R': 'DEF-upper_arm.R',
    'Arm_1_L': 'DEF-upper_arm.L.001',
    'Arm_1_R': 'DEF-upper_arm.R.001',
    'Arm_2_L': 'DEF-forearm.L',
    'Arm_2_R': 'DEF-forearm.R',
    'Wrist_Assist_L': 'DEF-forearm.L.001',
    'Wrist_Assist_R': 'DEF-forearm.R.001',
    'Wrist_L': 'DEF-hand.L',
    'Wrist_R': 'DEF-hand.R',
    'Finger_A_1_L': 'DEF-thumb.01.L',
    'Finger_A_2_L': 'DEF-thumb.02.L',
    'Finger_A_3_L': 'DEF-thumb.03.L',
    'Finger_A_1_R': 'DEF-thumb.01.R',
    'Finger_A_2_R': 'DEF-thumb.02.R',
    'Finger_A_3_R': 'DEF-thumb.03.R',
    'Finger_B_1_L': 'DEF-f_index.01.L',
    'Finger_B_2_L': 'DEF-f_index.02.L',
    'Finger_B_3_L': 'DEF-f_index.03.L',
    'Finger_B_1_R': 'DEF-f_index.01.R',
    'Finger_B_2_R': 'DEF-f_index.02.R',
    'Finger_B_3_R': 'DEF-f_index.03.R',
    'Finger_C_1_L': 'DEF-f_middle.01.L',
    'Finger_C_2_L': 'DEF-f_middle.02.L',
    'Finger_C_3_L': 'DEF-f_middle.03.L',
    'Finger_C_1_R': 'DEF-f_middle.01.R',
    'Finger_C_2_R': 'DEF-f_middle.02.R',
    'Finger_C_3_R': 'DEF-f_middle.03.R',
    'Finger_D_1_L': 'DEF-f_ring.01.L',
    'Finger_D_2_L': 'DEF-f_ring.02.L',
    'Finger_D_3_L': 'DEF-f_ring.03.L',
    'Finger_D_1_R': 'DEF-f_ring.01.R',
    'Finger_D_2_R': 'DEF-f_ring.02.R',
    'Finger_D_3_R': 'DEF-f_ring.03.R',
    'Finger_E_1_L': 'DEF-f_pinky.01.L',
    'Finger_E_2_L': 'DEF-f_pinky.02.L',
    'Finger_E_3_L': 'DEF-f_pinky.03.L',
    'Finger_E_1_R': 'DEF-f_pinky.01.R',
    'Finger_E_2_R': 'DEF-f_pinky.02.R',
    'Finger_E_3_R': 'DEF-f_pinky.03.R',

    'Knee_L': 'DEF-knee.L',
    'Elbow_L': 'DEF-elbow.L',
    'Knee_R': 'DEF-knee.R',
    'Elbow_R': 'DEF-elbow.R',

    # Special NPCs
    'Head_Cheek_L': 'DEF-head_cheek.L',
    'Head_Cheek_R': 'DEF-head_cheek.R',

    'Ear_L': 'DEF-ear.L',
    'Ear_R': 'DEF-ear.R',

    'Head_Intercostal': 'DEF-head_intercostal',
    'Eyebrow_L': 'DEF-head_eyebrow.L',
    'Eyebrow_R': 'DEF-head_eyebrow.R',

    'Head_Eyeblow_L': 'DEF-head_eyebrow.L',
    'Head_EyeblowInside_L': 'DEF-head_eyebrow_inside.L',
    'Head_EyeblowOutside_L': 'DEF-head_eyebrow_outside.L',
    'Head_Eyeblow_R': 'DEF-head_eyebrow.R',
    'Head_EyeblowInside_R': 'DEF-head_eyebrow_inside.R',
    'Head_EyeblowOutside_R': 'DEF-head_eyebrow_outside.R',

    'Mouth_Joe': 'DEF-mouth_jaw',
    'Mouth_Corner_L': 'DEF-mouth_corner.L',
    'Mouth_Corner_R': 'DEF-mouth_corner.R',

    # Callie's hair
    'Nape_L': 'DEF-nape.L',
    'Nape_R': 'DEF-nape.R',
    'Z_Nape_L': 'DEF-nape.L.001',
    'Z_Nape_R': 'DEF-nape.R.001',
    'Bangs_1': 'DEF-bangs',
    'Bangs_2': 'DEF-bangs.001',
    'Bangs_3': 'DEF-bangs.002',

    'hair': 'DEF-hair',
    'hair1_L': 'DEF-hair.L',
    'hair2_L': 'DEF-hair.L.001',
    'hair3_L': 'DEF-hair.L.002',
    'hair4_L': 'DEF-hair.L.003',
    'hair5_L': 'DEF-hair.L.004',
    'z_hair_L': 'DEF-hair.L.005',
    'upper_hair_L': 'DEF-upper_hair.L',
    'z_upper_hair_L': 'DEF-upper_hair.L.001',

    'hair1_R': 'DEF-hair.R',
    'hair2_R': 'DEF-hair.R.001',
    'hair3_R': 'DEF-hair.R.002',
    'hair4_R': 'DEF-hair.R.003',
    'hair5_R': 'DEF-hair.R.004',
    'z_hair_R': 'DEF-hair.R.005',
    'upper_hair_R': 'DEF-upper_hair.R',
    'z_upper_hair_R': 'DEF-upper_hair.R.001',

    # Marie's stuff
    'Ring_root': 'DEF-ring_root',
    'Ring_R': 'DEF-ring.R',
    'z_Ring_R': 'DEF-ring.R.001',
    'Ring_L': 'DEF-ring.L',
    'z_Ring_L': 'DEF-ring.L.001',
    'Ring_F': 'DEF-ring.F',
    'z_Ring_F': 'DEF-ring.F.001',
    'Ring_B': 'DEF-ring.B',
    'z_Ring_B': 'DEF-ring.B.001',
    'nape1': 'DEF-nape',
    'nape2': 'DEF-nape.001',
    'z_nape': 'DEF-nape.002',

    'Cloth_Skirt': 'DEF-cloth_skirt',
    'assist_Skirt_1_L': 'DEF-skirt_assist.L',
    'assist_Skirt_1_R': 'DEF-skirt_assist.R',

    # Frye
    'Assist_Thigh_L': 'DEF-thigh_assist.L',
    'Assist_Thigh_R': 'DEF-thigh_assist.R',
    'Head_Eyeblow_L': 'DEF-eyebrow.L',
    'Head_Eyeblow_R': 'DEF-eyebrow.R',
    'UpperEye_01_L': 'DEF-upper_eye.L',
    'UpperEye_02_L': 'DEF-upper_eye.L.001',
    'UpperEye_03_L': 'DEF-upper_eye.L.002',
    'UpperEye_04_L': 'DEF-upper_eye.L.003',
    'UpperEye_05_L': 'DEF-upper_eye.L.004',
    'UpperEye_01_R': 'DEF-upper_eye.R',
    'UpperEye_02_R': 'DEF-upper_eye.R.001',
    'UpperEye_03_R': 'DEF-upper_eye.R.002',
    'UpperEye_04_R': 'DEF-upper_eye.R.003',
    'UpperEye_05_R': 'DEF-upper_eye.R.004',
    'Eyelid_Lower_L': 'DEF-eyelid_lower.L',
    'Eyelid_Lower_R': 'DEF-eyelid_lower.R',
    'Eyelid_Upper_L': 'DEF-eyelid_upper.L',
    'Eyelid_Upper_R': 'DEF-eyelid_upper.R',

    'Hair_1': 'DEF-hair',
    'Hair_2': 'DEF-hair.001',
    'Hair_3': 'DEF-hair.002',
    'Hair_4': 'DEF-hair.003',
    'Hair_5': 'DEF-hair.004',
    'Hair_6': 'DEF-hair.005',
    'Mouse_L': 'DEF-mouth.L',
    'Mouse_R': 'DEF-mouth.R',
    'Chin_Lower': 'DEF-chin_lower',
    'Assist_Thigh_L': 'DEF-thigh_assist.L',
    'Assist_Thigh_R': 'DEF-thigh_assist.R',

    'Lip_Upper': 'DEF-lip_upper',
    'Lip_Lower': 'DEF-lip_lower',
    'Tongue_1': 'DEF-tongue',
    'Tongue_2': 'DEF-tongue.001',
    'Teeth_Lower': 'DEF-teeth_lower',
    'Teeth_Upper': 'DEF-teeth_upper',
    'Teeth_Fang_L': 'DEF-teeth_fang.L',
    'Teeth_Fang_R': 'DEF-teeth_fang.R',
}

CHAR_LOOKUP = {}

CHAR_LOOKUP['idolb'] = {}
